### ISSUE TITLE
Incoming japanese chat messages are not getting translated in Challenge Quests

### ISSUE THREAD

**Issue by flyergo** [cyberkitsune/PSO2Proxy#151] opened 2015-03-28 20:23 UTC
Hello, this issue bugged me already for some time. 
I could finally take a closer look at this. First I tought it is a problem with the configuration of my system, but this doesn't seem to be the case. I tested it just now on the public PSO2Proxy. 

And here is the result:

![translation_issue](https://cloud.githubusercontent.com/assets/10029199/6882726/d1373774-d58f-11e4-9865-21061ce6112a.png)

Kurumi was at first not in my party then I invited her an let her say the same "Hello" message in japanese.

It seems like translation only works for people in your party, but not for nearby players.
I tested this on both a private/local (Google/Goslate) and the public (Bing/Microsofttranslator) PSO2Proxy.
Neither seems to work. Can somebody maybe look into this?

**Comment by kamijoutouma** [comment] 2015-06-04 04:54
Refer to my second comment in the issue i mention this issue in.

After that this can be closed

**Comment by cyberkitsune** [comment] 2015-07-08 01:39
Duplicate of #152

**Closed by cyberkitsune** 2015-07-08 01:39 UTC
Labels: bug, packet-work-needed
